# Generated by Django 6.0 on 2025-12-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laba', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='text',
        ),
    ]
